// <auto-generated />
namespace SchoenyAzureContactMgr.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class AddBoleanColumnToGameType : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddBoleanColumnToGameType));
        
        string IMigrationMetadata.Id
        {
            get { return "201412242242551_AddBoleanColumnToGameType"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
